enum CALLBACK_DATA {
  SUBJECT_CHANGE_NAME = 'SUBJECT_CHANGE_NAME',
  SUBJECT_MAKE_GENERAL = 'SUBJECT_MAKE_GENERAL',
  SUBJECT_MAKE_NON_GENERAL = 'SUBJECT_MAKE_NON_GENERAL',
  SUBJECT_DISCARD = 'SUBJECT_DISCARD',
  SUBJECT_UNDO = 'SUBJECT_UNDO',
  SUBJECT_REDO = 'SUBJECT_REDO',
  SUBJECT_SAVE = 'SUBJECT_SAVE',
}

export { CALLBACK_DATA };
