const LangData: { [lang_key: string]: { [value: string]: string }; } = {
  'en': {
    'language-name': '🏴󠁧󠁢󠁥󠁮󠁧󠁿 English',
    'language-code': 'en',
    'subject-list': '📝 Subject list',
    'calendar': '📅 Calendar',
    'remove-subject': '⛔️ Remove subject',
    'header': '✏️ Header',
    'body': '📖 Body',
    'required': '🔴 Required',
    'dispensable': '🟡 Dispensable',
    'send-on': '📅 Send on',
    'link-subject': '🔗 Subject',
    'deadline': '📅 Deadline',
    'name': '✏️ Name',
    'general': '🟢 General',
    'non-general': '🟡 Non-general',
    'task': '✏️ Task',

    'discard': '🛑 Discard',
    'save': '✅ Save',
    'reset': '🔄 Reset',
    'undo': '↩️ Undo',
    'redo': '↪️ Redo',
  },
  'ua': {
    'language-name': '🇺🇦 Українська',
    'language-code': 'ua',
    'subject-list': '📝 Перелік предметів',
    'calendar': '📅 Календар',
    'remove-subject': '⛔️ Вилучити предмет',
    'header': '✏️ Заголовок',
    'body': '📖 Основна частина',
    'required': '🔴 Обов\'язковий',
    'dispensable': '🟡 Необов\'язковий',
    'send-on': '📅 Надіслати о',
    'link-subject': '🔗 Предмет',
    'deadline': '📅 Дедлайн',
    'name': '✏️ Назва',
    'general': '🟢 Загальний',
    'non-general': '🟡 Вибірковий',
    'task': '✏️ Завдання',

    'discard': '🛑 Відмінити',
    'save': '✅ Зберегти',
    'reset': '🔄 Скинути',
    'undo': '↩️ Відмінити',
    'redo': '↪️ Повторити',
  },
};

export { LangData };
