enum CALLBACK_DATA {
  SPLIT_SYMBOL = '_',

  SUBJECT_CHANGE_NAME = 'SUBJECT_CHANGE_NAME',
  SUBJECT_MAKE_GENERAL = 'SUBJECT_MAKE_GENERAL',
  SUBJECT_MAKE_NON_GENERAL = 'SUBJECT_MAKE_NON_GENERAL',
  SUBJECT_DISCARD = 'SUBJECT_DISCARD',
  SUBJECT_UNDO = 'SUBJECT_UNDO',
  SUBJECT_REDO = 'SUBJECT_REDO',
  SUBJECT_RESET = 'SUBJECT_RESET',
  SUBJECT_SAVE = 'SUBJECT_SAVE',

  LINK_SUBJECT = 'LINK_SUBJECT',
  REMOVE_SUBJECT = 'REMOVE_SUBJECT',
  DISCARD_PEEK_SUBJECT = 'DISCARD_PEEK_SUBJECT',

  SUBJECT_SWITCH_PERSONAL = 'SUBJECT_SWITCH_PERSONAL',
  SUBJECT_SAVE_PERSONAL_LIST = 'SUBJECT_SAVE_PERSONAL_LIST',

  NOTIFICATION_CHANGE_HEADER = 'NOTIFICATION_CHANGE_HEADER',
  NOTIFICATION_CHANGE_BODY = 'NOTIFICATION_CHANGE_BODY',
  NOTIFICATION_CHANGE_DATE = 'NOTIFICATION_CHANGE_DATE',
  NOTIFICATION_CHANGE_DEADLINE = 'NOTIFICATION_CHANGE_DEADLINE',
  NOTIFICATION_SET_SUBJECT = 'NOTIFICATION_SET_SUBJECT',
  NOTIFICATION_SET_REQUIRED = 'NOTIFICATION_SET_REQUIRED',
  NOTIFICATION_SET_DISPENSABLE = 'NOTIFICATION_SET_DISPENSABLE',
  NOTIFICATION_DISCARD = 'NOTIFICATION_DISCARD',
  NOTIFICATION_RESET = 'NOTIFICATION_RESET',
  NOTIFICATION_SAVE = 'NOTIFICATION_SAVE',

  SETTINGS_SUBJECTS = 'SETTINGS_SUBJECTS',
  SETTINGS_CALENDAR = 'SETTINGS_CALENDAR',
  SETTINGS_SAVE = 'SETTINGS_SAVE',
  SETTINGS_DISCARD = 'SETTINGS_DISCARD',

  DEADLINE_CHANGE_TASK = 'DEADLINE_CHANGE_TASK',
  DEADLINE_CHANGE_DATE = 'DEADLINE_CHANGE_DATE',
  DEADLINE_SET_SUBJECT = 'DEADLINE_SET_SUBJECT',
  DEADLINE_SAVE = 'DEADLINE_SAVE',
  DEADLINE_DISCARD = 'DEADLINE_DISCARD',
}

export { CALLBACK_DATA };
