export enum SceneIDs {
  NEW_SUBJECT = 'NEW_SUBJECT_SCENE',

  PEEK_PERSONAL = 'PEEK_PERSONAL',
  NEW_TASK = 'NEW_TASK',
  REMINDER = 'REMINDER',
  EDIT_PERSONAL_SUBJECTS = 'EDIT_PERSONAL_SUBJECTS',

  // Notification scene and subscenes ids
  NOTIFICATION = 'NOTIFICATION_SCENE',
  NOTIFICATION_SUBJECT = 'NOTIFICATION_SUBJECT_SCENE',

  // Settings scene and subscenes ids
  SETTINGS = 'SETTINGS_SCENE',
  SETTINGS_LANGUAGE = 'SETTINGS_LANGUAGE_SCENE',
  SETTINGS_CALENDAR = 'SETTINGS_CALENDAR_SCENE',
  SETTINGS_REMINDERS = 'SETTINGS_REMINDERS',
  SETTINGS_REMINDER_OFFSET = 'SETTINGS_REMINDER_OFFSET',
}
