export enum SceneIDs {
  NEW_SUBJECT = 'NEW_SUBJECT_SCENE',
  NOTIFICATION = 'NOTIFICATION_SCENE',
  SETTINGS = 'SETTINGS_SCENE',
  PEEK_PERSONAL = 'PEEK_PERSONAL',
  NEW_TASK = 'NEW_TASK',
  REMINDER = 'REMINDER',
  EDIT_PERSONAL_SUBJECTS = 'EDIT_PERSONAL_SUBJECTS',
  EDIT_LANGUAGE = 'EDIT_LANGUAGE',
  EDIT_CALENDAR = 'EDIT_CALENDAR',
}
